### PR TITLE
generate blocks for complete music, including previously played notes

### PR DESCRIPTION
**Pull request by DolevArtzi**

### CODE REVIEW

**Comment by DolevArtzi** [comment]
the block has a provisional name

**Comment by DolevArtzi** [comment]
also, it currently appends all the notes that are in the `noteList`, which could present a problem and cause lag if there are hundreds of notes in the note list, e.g. after playing multiple `generate new music` blocks.

**Comment by DolevArtzi** [comment]
TODO: chop off notes to be used at 20, give an alert, in the alert describe how to clear note list

**Comment by pmalacho-mit** [comment]
@DolevArtzi need to get this branch current with `parker-ProgrammaticallyAddBlocks` branch

**Pull request merged**
